version: '3.8'

services:
  app:
    build:
      context: .
    volumes:
      - ./go:/go
    ports:
      - "8080:8080"
    depends_on:
      - db
      - cache
      - queue

  nginx:
    build:
      context: ./nginx
    volumes:
      - ./nginx:/etc/nginx/conf.d
    ports:
      - "80:80"
    depends_on:
      - app

  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db:/var/lib/mysql

  cache:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes:
      - cache:/data

  queue:
    image: rabbitmq:3.8-management
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - queue:/var/lib/rabbitmq

volumes:
  db:
  queue:
  cache:
    driver: local